# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(678, 535)
        Form.setMinimumSize(QtCore.QSize(620, 535))
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(350, 10, 321, 511))
        self.scrollArea.setMinimumSize(QtCore.QSize(281, 231))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 302, 4000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 4000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 301, 791))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.IS_ZD = QtWidgets.QCheckBox(Form)
        self.IS_ZD.setGeometry(QtCore.QRect(11, 500, 95, 21))
        self.IS_ZD.setObjectName("IS_ZD")
        self.BACK = QtWidgets.QPushButton(Form)
        self.BACK.setGeometry(QtCore.QRect(274, 497, 75, 23))
        self.BACK.setObjectName("BACK")
        self.SAVE = QtWidgets.QPushButton(Form)
        self.SAVE.setGeometry(QtCore.QRect(193, 11, 75, 23))
        self.SAVE.setObjectName("SAVE")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(11, 11, 71, 21))
        self.label.setObjectName("label")
        self.TEXT_CORRECTION = QtWidgets.QPushButton(Form)
        self.TEXT_CORRECTION.setGeometry(QtCore.QRect(112, 497, 75, 23))
        self.TEXT_CORRECTION.setObjectName("TEXT_CORRECTION")
        self.ADD_PPT = QtWidgets.QPushButton(Form)
        self.ADD_PPT.setGeometry(QtCore.QRect(193, 497, 75, 23))
        self.ADD_PPT.setObjectName("ADD_PPT")
        self.EXPORT = QtWidgets.QPushButton(Form)
        self.EXPORT.setGeometry(QtCore.QRect(112, 11, 75, 23))
        self.EXPORT.setObjectName("EXPORT")
        self.LOAD = QtWidgets.QPushButton(Form)
        self.LOAD.setGeometry(QtCore.QRect(274, 11, 75, 23))
        self.LOAD.setObjectName("LOAD")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(11, 40, 331, 451))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.IS_ZD.setText(_translate("Form", "是否为照读稿"))
        self.BACK.setText(_translate("Form", "返回"))
        self.SAVE.setText(_translate("Form", "保存"))
        self.label.setText(_translate("Form", "编辑栏"))
        self.TEXT_CORRECTION.setText(_translate("Form", "语法纠错"))
        self.ADD_PPT.setText(_translate("Form", "添加PPT"))
        self.EXPORT.setText(_translate("Form", "导出"))
        self.LOAD.setText(_translate("Form", "加载"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
