# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Index.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(560, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(560, 520))
        Form.setMaximumSize(QtCore.QSize(560, 520))
        self.editor_but = QtWidgets.QPushButton(Form)
        self.editor_but.setGeometry(QtCore.QRect(10, 10, 271, 251))
        self.editor_but.setObjectName("editor_but")
        self.oral_but = QtWidgets.QPushButton(Form)
        self.oral_but.setGeometry(QtCore.QRect(280, 260, 271, 251))
        self.oral_but.setObjectName("oral_but")
        self.practice_but = QtWidgets.QPushButton(Form)
        self.practice_but.setGeometry(QtCore.QRect(280, 10, 271, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.practice_but.sizePolicy().hasHeightForWidth())
        self.practice_but.setSizePolicy(sizePolicy)
        self.practice_but.setObjectName("practice_but")
        self.free_but = QtWidgets.QPushButton(Form)
        self.free_but.setGeometry(QtCore.QRect(10, 260, 271, 251))
        self.free_but.setObjectName("free_but")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.editor_but.setText(_translate("Form", "编辑稿件"))
        self.oral_but.setText(_translate("Form", "口语训练"))
        self.practice_but.setText(_translate("Form", "对稿演练"))
        self.free_but.setText(_translate("Form", "自由演练"))
